config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      root 'home#index', as: :unauthenticated_root
    end
  end
  
  authenticated :user do
    root 'posts#index', as: :authenticated_root
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_rich_text :content
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, :content, presence: true

  scope :latest, -> { order(created_at: :desc) }
  scope :popular, -> { order(likes_count: :desc) }

  def liked?(user)
    !!self.likes.find{ |like| like.user_id == user.id }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to @post, alert: "Error creating a comment: #{@comment.errors.full_messages.join(", ")}" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: "Comment was successfully destroyed."
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'landing'

  def index
    @name = 'Connectory'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    Like.create(user: current_user, post: @post)
    redirect_to @post
  end

  def destroy
    like = Like.where(user_id: current_user.id, post_id: @post.id).first
    like.destroy
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.popular.latest
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to authenticated_root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'bg-green-400',
      error: 'bg-red-400',
      alert: 'bg-yellow-700',
      notice: 'bg-blue-400'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<section class="bg-gray-100 rounded shadow p-5 mt-5">
  <div class="flex">
    <figure style="min-width: 50px;">
      <img src="https://avatars.dicebear.com/api/bottts/rodkd.svg" alt="avatar" width='50' height='50'>
    </figure>
    <div class="pl-5">
      <p class="mb-2">
        <span class="font-bold italic mr-5">
          <%= comment.user.name.familiar %>
        </span>
        <span><%= time_ago_in_words(comment.created_at) %> ago</span>
      </p>
      <p><%= comment.content %></p>
    </div>
  </div>
  <% if current_user == comment.user %>
    <div class="text-right">
      <%= link_to 'Destroy', post_comment_path(comment.post, comment), method: :delete, class: 'text-red-500 hover:text-red-700 underline' %>
    </div>
  <% end %>
</section>

app/views/home/index.html.erb
<div class="w-full h-full flex flex-col justify-center items-center">
  <h1 class="text-4xl pb-2 border-b-2 border-gray-400">
    Welcome to <span class="text-blue-600 font-medium"><%= @name %></span> 🤟🏼
  </h1>
  <p class="mt-3 text-lg text-gray-500 font-light italic">
    A place where you can help anyone!
  </p>
  <div class="mt-5 text-center">
    <%= link_to 'Log In', new_user_session_path, class: 'text-blue-500 text-2xl underline' %>
    <span class="mx-3">or</span>
    <%= link_to 'Create an account', new_user_registration_path, class: 'text-blue-500 text-2xl underline' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Connectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100 h-full">
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>

    <div class="py-8 px-2 md:px-32 xl:px-60">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Connectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100 h-full">
    <%= render 'shared/alerts' %>

    <div class="max-w-sm mx-auto flex flex-col items-center justify-center px-2">
      <h1 class="text-4xl font-medium text-blue-600 mt-16 mb-5">
        <%= link_to 'Connectory', unauthenticated_root_path %>
      </h1>
      <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Connectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100 h-full">
    <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="bg-red-500 p-2 mb-3 text-white">
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-8">
    <%= form.text_field :title, placeholder: 'Title', class: 'block border border-grey-light w-full p-3 rounded' %>
  </div>

  <div class="field mb-4">
    <%= form.rich_text_area :content, placeholder: "What's your question?..." %>
  </div>

  <div class="actions">
    <%= form.submit 'Publish', class: 'w-full text-center py-3 rounded bg-green-500 text-white hover:bg-green-600 duration-300 cursor-pointer' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="bg-white rounded shadow-md p-5 mb-5">
  <header>
    <p class="text-right text-sm text-gray-400"><%= time_ago_in_words(post.created_at) %> ago</p>
    <h3 class="text-xl mb-1"><%= post.title %></h3>
    <p class="text-md text-gray-500 italic mb-3">
      by <%= post.user.name.familiar %>
    </p>
  </header>
  <main>
    <p class="text-sm text-gray-400 mb-3">
      <%= truncate(strip_tags(post.content.to_s), length: 150) %>
    </p>
  </main>
  <hr>
  <footer class="mt-3 text-right">
    <div class="flex items-center justify-between">
      <div>
        <% if current_user == post.user %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 hover:text-red-700 underline' %>
          <%= link_to 'Edit', edit_post_path(post), class: 'text-green-500 hover:text-green-700 underline ml-3' %>
        <% end %>
      </div>
      <div class="flex items-center">
        <span class="flex items-center">
          <svg width="30" height="30" viewBox="0 0 80 80" fill="red" xmlns="http://www.w3.org/2000/svg">
            <path d="M39.7279 23.9285L36.8995 21.1C34.274 18.4745 30.713 16.9995 27 16.9995C23.287 16.9995 19.726 18.4745 17.1005 21.1C14.475 23.7255 13 27.2865 13 30.9995C13 34.7125 14.475 38.2735 17.1005 40.899L31.1813 54.9798C31.2016 55.0003 31.222 55.0208 31.2425 55.0413L38.3136 62.1124C38.7041 62.5029 39.216 62.6982 39.7279 62.6982" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
            <path d="M39.728 23.9283L42.5563 21.1C45.1818 18.4745 48.7428 16.9995 52.4558 16.9995C56.1688 16.9995 59.7298 18.4745 62.3553 21.1C64.9808 23.7255 66.4558 27.2865 66.4558 30.9995C66.4558 34.7125 64.9808 38.2735 62.3553 40.899L41.1421 62.1122C40.7516 62.5027 40.2398 62.698 39.728 62.698" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
          <%= post.likes_count %>
        </span>
        <%= link_to 'Show', post, class: 'py-2 px-5 ml-5 bg-blue-500 hover:bg-blue-700 duration-300 text-white rounded' %>
      </div>
    </div>
  </footer>
</article>

app/views/posts/edit.html.erb
<div class="sm:max-w-screen-lg mx-auto flex flex-col items-center justify-center">
  <div class="bg-white p-5 rounded shadow-md text-black w-full">
    <div class="flex items-center justify-between mb-5">
      <h1 class="text-4xl">Edit question</h1>
      <%= link_to 'Go to question', @post, class: 'text-blue-500 underline hover:text-blue-700' %>
    </div>
    <%= render 'form', post: @post %>
    <div class="text-center mt-5">
      <%= link_to 'Back', authenticated_root_path, class: 'text-blue-500 underline hover:text-blue-700' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="flex">
  <section class="w-full px-12 lg:px-40">
    <h2 class="text-2xl mb-5 text-center">Questions</h2>
    <%= render @posts %>
  </section>
</div>

app/views/posts/new.html.erb
<div class="max-w-screen-lg mx-auto flex flex-col items-center justify-center">
  <div class="bg-white p-5 rounded shadow-md text-black w-full">
    <h1 class="text-4xl mb-5">Create a new question</h1>
    <%= render 'form', post: @post %>
    <div class="text-center mt-5">
      <%= link_to 'Back', authenticated_root_path, class: 'text-blue-500 underline hover:text-blue-700' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<article class="bg-white rounded shadow-md p-5">
  <header>
    <div class="flex justify-between items-center mb-5">
      <%= link_to '👈 Back to home', authenticated_root_path, class: 'text-blue-500 underline hover:text-blue-700' %>
      <div class="flex items-center">
        <p class="text-right text-sm text-gray-400 mr-3">
          <%= time_ago_in_words(@post.created_at) %> ago
        </p>
        
        <% if @post.liked?(current_user) %>
          <%= button_to post_like_path(@post), method: :delete, class: 'focus:outline-none' do %>
            <svg width="50" height="50" viewBox="0 0 80 80" fill="red" xmlns="http://www.w3.org/2000/svg">
              <path d="M39.7279 23.9285L36.8995 21.1C34.274 18.4745 30.713 16.9995 27 16.9995C23.287 16.9995 19.726 18.4745 17.1005 21.1C14.475 23.7255 13 27.2865 13 30.9995C13 34.7125 14.475 38.2735 17.1005 40.899L31.1813 54.9798C31.2016 55.0003 31.222 55.0208 31.2425 55.0413L38.3136 62.1124C38.7041 62.5029 39.216 62.6982 39.7279 62.6982" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M39.728 23.9283L42.5563 21.1C45.1818 18.4745 48.7428 16.9995 52.4558 16.9995C56.1688 16.9995 59.7298 18.4745 62.3553 21.1C64.9808 23.7255 66.4558 27.2865 66.4558 30.9995C66.4558 34.7125 64.9808 38.2735 62.3553 40.899L41.1421 62.1122C40.7516 62.5027 40.2398 62.698 39.728 62.698" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          <% end %>
        <% else %>
          <%= button_to post_like_path(@post), method: :post, class: 'focus:outline-none' do %>
            <svg width="50" height="50" viewBox="0 0 80 80" fill="silver" xmlns="http://www.w3.org/2000/svg">
              <path d="M39.7279 23.9285L36.8995 21.1C34.274 18.4745 30.713 16.9995 27 16.9995C23.287 16.9995 19.726 18.4745 17.1005 21.1C14.475 23.7255 13 27.2865 13 30.9995C13 34.7125 14.475 38.2735 17.1005 40.899L31.1813 54.9798C31.2016 55.0003 31.222 55.0208 31.2425 55.0413L38.3136 62.1124C38.7041 62.5029 39.216 62.6982 39.7279 62.6982" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M39.728 23.9283L42.5563 21.1C45.1818 18.4745 48.7428 16.9995 52.4558 16.9995C56.1688 16.9995 59.7298 18.4745 62.3553 21.1C64.9808 23.7255 66.4558 27.2865 66.4558 30.9995C66.4558 34.7125 64.9808 38.2735 62.3553 40.899L41.1421 62.1122C40.7516 62.5027 40.2398 62.698 39.728 62.698" stroke="#C2CCDE" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          <% end %>
        <% end %>
        
      </div>
    </div>
    <h1 class="text-4xl mb-3"><%= @post.title %></h1>
    <div class="mb-8 flex">
      <span class="text-gray-500 italic mr-12">by <%= @post.user.name.familiar %></span>
      <% if current_user == @post.user %>
        <div>
          <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 hover:text-red-700 underline' %>
          <%= link_to 'Edit', edit_post_path(@post), class: 'text-green-500 hover:text-green-700 underline ml-3' %>
        </div>
      <% end %>
    </>
  </header>
  <main class="mb-5">
    <p><%= @post.content %></p>
  </main>
  <footer>
    <h2 class="text-2xl mb-5">Comments (<%= @post.comments_count %>)</h2>

    <%= form_with(model: [@post, @comment], method: :post) do |form| %>
      <div class="mb-3">
        <%= form.rich_text_area :content, placeholder: "Comment..." %>
      </div>
      <%= form.submit 'Comment', class: 'w-full text-center py-3 rounded bg-green-500 text-white hover:bg-green-600 duration-300 cursor-pointer' %>
    <% end %>

    <section class="mt-5">
      <%= render @post.comments %>
    </section>
  </footer>
</article>

app/views/shared/_alerts.html.erb
<% flash.each do |alert_type, message| %>
  <div class="p-5 <%= alert_class_for(alert_type) %>">
    <span class="text-white"><%= message %></span>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-32 bg-white shadow sm:items-baseline w-full">
  <div class="mb-2 sm:mb-0">
    <a href="/" class="text-2xl no-underline font-medium text-blue-600 mr-5">
      Connectory
    </a>
    <%= link_to 'Publish', new_post_path, class: 'text-lg text-blue-500 no-underline text-grey-darkest hover:text-blue-dark ml-2' %>
  </div>
  <div>
    <%= link_to current_user.name.familiar, edit_user_registration_path, class: 'text-lg text-blue-500 no-underline text-grey-darkest hover:text-blue-dark ml-2' %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'text-lg text-red-500 no-underline text-grey-darkest hover:text-blue-dark ml-2' %>
  </div>
</nav>